### PR TITLE
test: fixes flaky tests due to asynchronous karaf startup (#105)

### LINKED ISSUE #105: Karaf tests are flaky due to karaf async startup
Karaf is started asynchronously which causes race condition. When test is run connection to karaf is checked (it is running) but test jar is not yet started causing test failures. Not reproducible (yet) on Bender.

### PR DESCRIPTION
**Pull request by MarcinVaadin**
## Description

Fixes flaky tests due to asynchronous Karaf startup

Fixes #105

## Type of change

- [ ] Bugfix
- [ ] Feature
- [x] Test

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

File: test-containers/karaf/karaf-run/src/test/java/com/vaadin/flow/karaf/smoketest/WaitForUrlTest.java [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+ * no maven server plugin which runs the server and wait when it becomes
+ * ready and then switch to the next maven phase.
+ * With the current configuration the server start is done async in the
+ * separate JVM and no one waits for its readiness.
+ * As a result IT tests starts immediately and this workaround is used
+ * to wait when HTTP server starts to handle HTTP requests.
+ */
+public abstract class WaitForUrlTest extends ChromeBrowserTest {
+
+    protected Optional<HttpURLConnection> waitAndGetUrl(URL url, int count)
```
Comment (mcollovati) [inline test-containers/karaf/karaf-run/src/test/java/com/vaadin/flow/karaf/smoketest/WaitForUrlTest.java:22]: Just a suggestion, but it is up to you to decide the final implementation.
I would use `waitUntil()` utility for this check that IMO simplifies the code and may be a more familiar pattern for developers that already use Testbench. It will also use a loop instead of recursion, so it avoid potential stack overflow exception.

In propose something similar to this

```java
    protected HttpURLConnection waitAndGetUrl(URL url, int timeout) {
        return waitUntil(unused -> {
            try {
                HttpURLConnection connection = (HttpURLConnection) url
                        .openConnection();
                connection.connect();
                // check if resource is available
                if (connection.getResponseCode() == HttpURLConnection.HTTP_OK) {
                    return connection;
                }
            } catch (IOException exception) {
                // ignore
            }
            return null;
        }, timeout);
    }
```

Comment (MarcinVaadin) [reply test-containers/karaf/karaf-run/src/test/java/com/vaadin/flow/karaf/smoketest/WaitForUrlTest.java:22]: Sure, thanks, I'll check and commit update.

**Review by mcollovati — APPROVED** [review]
